/**
 * Schema Type Definitions
 *
 * This file is auto-generated by openapi-typescript from the Cartesi rollup OpenAPI spec.
 * Run `npm run codegen` to regenerate.
 *
 * For the generalized framework, this provides the base types needed for the rollup server.
 */

export interface paths {
  '/finish': {
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['Finish'];
        };
      };
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['RollupRequest'];
          };
        };
        202: {
          content: {
            'text/plain': string;
          };
        };
      };
    };
  };
  '/notice': {
    post: {
      requestBody: {
        content: {
          'application/json': {
            payload: string;
          };
        };
      };
      responses: {
        200: unknown;
      };
    };
  };
  '/report': {
    post: {
      requestBody: {
        content: {
          'application/json': {
            payload: string;
          };
        };
      };
      responses: {
        200: unknown;
      };
    };
  };
  '/voucher': {
    post: {
      requestBody: {
        content: {
          'application/json': {
            destination: string;
            payload: string;
          };
        };
      };
      responses: {
        200: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    Finish: {
      status: 'accept' | 'reject';
    };
    RollupRequest: {
      request_type: 'advance_state' | 'inspect_state';
      data: components['schemas']['Advance'] | components['schemas']['Inspect'];
    };
    Advance: {
      metadata: {
        msg_sender: string;
        epoch_index: number;
        input_index: number;
        block_number: number;
        timestamp: number;
      };
      payload: string;
    };
    Inspect: {
      payload: string;
    };
  };
}
